Repository TaskMaster873/DRFWClient, pull requests merged in 2023-03, with the labels that each got.

#212 Update schedule creator
  src/src/engine/api/APIManager.ts
  src/src/engine/components/ComponentPopupSchedule.tsx
  src/src/engine/components/ComponentScheduleCreate.tsx
  src/src/engine/components/SelectDate.tsx
  src/src/engine/components/SelectDepartment.tsx
  src/src/engine/messages/FormMessages.ts
  src/src/engine/pages/CreateSchedule.tsx
  src/src/engine/utils/DateManager.ts
Labels: enhancement

#214 Fixed navbar admin links
  src/src/engine/RoutesPath.ts
  src/src/engine/api/APIManager.ts
  src/src/engine/components/NavigationBar.tsx
Labels: enhancement

#228 Update APIManager.ts
  src/src/engine/api/APIManager.ts
Labels: bug

#227 Update ComponentHomePage.tsx
  src/src/engine/components/ComponentHomePage.tsx
Labels: bug

#245 Complete manage availabilities
  src/src/engine/api/APIManager.ts
  src/src/engine/components/ComponentAvailabilitiesPopup.tsx
  src/src/engine/components/ComponentPopupSchedule.tsx
  src/src/engine/pages/Availabilities.tsx
  src/src/engine/types/EmployeeAvailabilities.ts
  src/src/engine/utils/DateManager.ts
Labels: enhancement

#253 Icon color fix
  src/src/engine/components/AvailabilitiesList.tsx
  src/src/engine/components/ComponentDepartmentList.tsx
Labels: bug, enhancement

#256 fix dark theme + buttons of modals
  src/src/deps/css/index.css
  src/src/engine/components/ComponentEditJobTitles.tsx
  src/src/engine/components/ComponentEditSkills.tsx
  src/src/engine/components/ComponentEmployeeList.tsx
  src/src/engine/components/ComponentPopupSchedule.tsx
Labels: bug, enhancement

#259 FINALE REFACTOR
  src/Constants/testConstants.ts
  src/__tests__/testAddDepartment.test.js
  src/__tests__/testAddEmployee.test.js
  src/__tests__/testChangePassword.test.js
  src/__tests__/testComponentPopupSchedule.test.js
  src/__tests__/testDepartmentList.test.js
  src/__tests__/testEditEmployee.test.js
  src/__tests__/testForgotPassword.test.js
  src/__tests__/testLoginComponent.test.js
  src/__tests__/testResetPasswordComponent.test.js
  src/src/engine/components/AvailabilitiesList.tsx
  src/src/engine/components/ComponentAvailabilities.tsx
  src/src/engine/components/ComponentDepartmentList.tsx
  src/src/engine/components/ComponentEditEmployee.tsx
  src/src/engine/components/ComponentEditJobTitles.tsx
  src/src/engine/components/ComponentEditSkills.tsx
  src/src/engine/components/ComponentEmployeeList.tsx
  src/src/engine/components/ComponentPopupSchedule.tsx
  src/src/engine/pages/AddEmployee.tsx
  src/src/engine/pages/Availabilities.tsx
  src/src/engine/pages/ChangePassword.tsx
  src/src/engine/pages/Departments.tsx
  src/src/engine/pages/Employees.tsx
  src/src/engine/types/Department.ts
  src/src/engine/types/Employee.ts
Labels: enhancement, FINALE

#263 FINAL Release GOLD
  firestore.rules
  package.json
  src/src/engine/Engine.tsx
  src/src/engine/api/APIManager.ts
  src/src/engine/api/APIUtils.ts
  src/src/engine/api/ServiceWorker.ts
  src/src/engine/components/ComponentAbout.tsx
  src/src/engine/components/ComponentAvailabilities.tsx
  src/src/engine/components/ComponentAvailabilitiesPopup.tsx
  src/src/engine/components/ComponentEditDepartment.tsx
  src/src/engine/components/ComponentEditJobTitles.tsx
  src/src/engine/components/ComponentLogin.tsx
  src/src/engine/messages/APIMessages.ts
  src/src/engine/messages/FormMessages.ts
Labels: IMPORTANT, FINALE, GOLD RELEASE
