Repository TaskMaster873/DRFWClient, pull requests merged in 2023-02, with the labels that each got.

#127 Preproduction Release
  src/Constants/Constants.ts
  src/Constants/testConstants.js
  src/__tests__/testAddEmployee.test.js
  src/__tests__/testLoginComponent.test.js
  src/src/engine/Engine.tsx
  src/src/engine/components/ComponentAddEmployee.tsx
  src/src/engine/components/ComponentAvailabilities.tsx
  src/src/engine/components/ComponentChangePassword.tsx
  src/src/engine/components/ComponentDepartmentList.tsx
  src/src/engine/components/ComponentEmployeeList.tsx
  src/src/engine/components/ComponentLogin.tsx
  src/src/engine/components/ComponentSchedule.tsx
  src/src/engine/components/NavigationBar.tsx
  src/src/engine/config/Config.ts
  src/src/engine/networking/PacketBuilder.ts
  src/src/engine/networking/WebsocketManager.ts
  src/src/engine/networking/opcodes/Opcodes.ts
  src/src/engine/networking/types/Packets.ts
  src/src/engine/pages/addEmployee.tsx
  src/src/engine/pages/availabilities.tsx
  src/src/engine/pages/departments.tsx
  src/src/engine/pages/employees.tsx
  src/src/engine/pages/schedule.tsx
  src/src/engine/types/Availability.ts
  src/src/engine/types/Department.ts
  src/src/engine/types/Employee.ts
Labels: preproduction

#129 Corvee remove config bypass
  src/__tests__/testAddEmployee.test.js
  src/__tests__/testChangePassword.test.js
  src/__tests__/testLoginComponent.test.js
  src/src/Application.tsx
  src/src/engine/Config.ts
  src/src/engine/components/ComponentAddDepartement.tsx
  src/src/engine/components/ComponentAddEmployee.tsx
  src/src/engine/components/ComponentAvailabilities.tsx
  src/src/engine/components/ComponentChangePassword.tsx
  src/src/engine/components/ComponentEmployeeList.tsx
  src/src/engine/components/ComponentLogin.tsx
  src/src/engine/components/ComponentSchedule.tsx
  src/src/engine/config/Config.ts
  src/src/engine/errors/FormErrorType.ts
  src/src/engine/messages/FormMessages.ts
  src/src/engine/messages/StatusMessage.ts
  src/src/engine/networking/Encryptem.ts
  src/src/engine/networking/PacketBuilder.ts
  src/src/engine/networking/WebsocketManager.ts
  src/src/engine/networking/types/Packets.ts
  src/src/engine/pages/departments.tsx
  src/src/engine/pages/employees.tsx
  src/src/engine/pages/schedule.tsx
  src/src/engine/types/AuthData.ts
  src/src/engine/types/AuthenticationStatus.ts
  src/src/engine/types/Department.ts
  src/src/engine/types/Employee.ts
  src/src/engine/types/Opcodes.ts
  src/src/engine/types/Packets.ts
  src/src/engine/utils/RegexValidator.tsx
Labels: documentation, enhancement

#139 fix addEmployee roles
  src/src/engine/Engine.tsx
  src/src/engine/api/APIManager.ts
  src/src/engine/components/ComponentAddEmployee.tsx
  src/src/engine/components/ComponentEmployeeList.tsx
  src/src/engine/pages/addEmployee.tsx
  src/src/engine/types/Employee.ts
Labels: enhancement

#154 Add dev emulator
  .firebaserc
  firebase.json
  firestore.indexes.json
  firestore.rules
  src/src/engine/api/APIManager.ts
  src/src/engine/api/config/FirebaseConfig.ts
Labels: enhancement

#168 Tests employee list
  emulatorSave/auth_export/accounts.json
  emulatorSave/firestore_export/all_namespaces/all_kinds/all_namespaces_all_kinds.export_metadata
  emulatorSave/firestore_export/all_namespaces/all_kinds/output-0
  package.json
  src/__tests__/testEmployeeList.test.js
  src/src/engine/components/ComponentEmployeeList.tsx
  src/src/engine/types/Employee.ts
Labels: tests

#179 Documented API methods
  src/src/engine/api/APIManager.ts
Labels: documentation

#201 MAJOR BUG FIX (3 part, more todo.)
  .gitignore
  package.json
  src/Constants/testConstants.ts
  src/__mocks__/fileMock.js
  src/__mocks__/styleMock.js
  src/html/index.html
  src/src/Application.tsx
  src/src/deps/css/Engine.css
  src/src/deps/css/cssForMiniCalendar.css
  src/src/deps/css/index.css
  src/src/engine/Engine.tsx
  src/src/engine/api/APIManager.ts
  src/src/engine/api/NotificationManager.ts
  src/src/engine/components/ComponentAddEmployee.tsx
  src/src/engine/components/ComponentChangePassword.tsx
  src/src/engine/components/ComponentEditEmployee.tsx
  src/src/engine/components/ComponentEmployeeList.tsx
  src/src/engine/components/ComponentForgotPassword.tsx
  src/src/engine/components/ComponentHomePage.tsx
  src/src/engine/components/ComponentLoadingBarSpinner.tsx
  src/src/engine/components/ComponentLogin.tsx
  src/src/engine/components/ComponentResetPassword.tsx
  src/src/engine/components/ComponentScheduleCreate.tsx
  src/src/engine/components/ComponentUserActionDropdown.tsx
  src/src/engine/components/NavigationBar.tsx
  src/src/engine/components/SelectDepartment.tsx
  src/src/engine/messages/FormMessages.ts
  src/src/engine/pages/AddEmployee.tsx
  src/src/engine/pages/CreateSchedule.tsx
  src/src/engine/pages/Departments.tsx
  src/src/engine/pages/EditEmployee.tsx
  src/src/engine/pages/Employees.tsx
  src/src/engine/pages/Login.tsx
  src/src/engine/pages/ResetPassword.tsx
  src/src/engine/pages/RouteNotFound.tsx
  src/src/engine/pages/ScheduleEmployee.tsx
  src/src/engine/types/Department.ts
  src/src/engine/types/Employee.ts
  src/src/engine/utils/RegexValidator.ts
  tsconfig.json
Labels: bug, documentation, enhancement, IMPORTANT, tests

#203 Edit department
  firestore.rules
  src/__tests__/testDepartmentList.test.js
  src/__tests__/testEmployeeList.test.js
  src/__tests__/testLoginComponent.test.js
  src/src/engine/api/APIManager.ts
  src/src/engine/components/ComponentDepartmentList.tsx
  src/src/engine/components/ComponentEditDepartment.tsx
  src/src/engine/components/ComponentEmployeeList.tsx
  src/src/engine/messages/FormMessages.ts
  src/src/engine/pages/Departments.tsx
  src/src/engine/types/Department.ts
  src/src/engine/types/Employee.ts
Labels: enhancement

#206 Filter refactor employee list + unit tests
  jest.config.js
  src/__tests__/testFilterEmployeeList.test.js
  src/src/engine/components/ComponentDepartmentList.tsx
  src/src/engine/components/ComponentEmployeeList.tsx
  src/src/engine/components/ComponentLoadingBarSpinner.tsx
  src/src/engine/components/ComponentSearchBar.tsx
  src/src/engine/components/FilterDepartmentCreateSchedule.tsx
  src/src/engine/pages/Employees.tsx
  src/src/engine/types/Employee.ts
  src/src/engine/types/StatesForDaypilot.ts
  src/src/engine/utils/Filter.ts
  src/src/engine/utils/FilterUtils.ts
Labels: enhancement, IMPORTANT, tests

#205 Added shift deletion
  firestore.rules
  src/Constants/testConstants.ts
  src/__tests__/testComponentPopupSchedule.test.js
  src/src/engine/api/APIManager.ts
  src/src/engine/components/ComponentLogin.tsx
  src/src/engine/components/ComponentPopupSchedule.tsx
  src/src/engine/components/ComponentScheduleCreate.tsx
  src/src/engine/messages/FormMessages.ts
  src/src/engine/pages/CreateSchedule.tsx
Labels: enhancement
